### ISSUE TITLE
Update ember-cli-htmlbars version

### ISSUE THREAD

**Issue by tobiasWenger** [eliksir/ember-progress#1]
Hi,
could you update the ember-cli-htmlbars version to get rid of the depreciation warnings?
Thanks..

**Comment by r22cky** [comment]
Hi! I just installed the addon on my ember prject and i got a deprecation warning. May be it was fix? I just wanted to let you know, here is the warning when lauching ember server:

DEPRECATION: ```Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars` at Function.Addon.lookup (/Users/devlecollectionist/Code/lecollectionist/customer-advising-dashboard/node_modules/ember-cli/lib/models/addon.js:1006:27)```

Thank you in advance! :)

**Comment by simenheg** [comment]
Thanks for the notice, @tobiasWenger and @r22cky.

I've updated the Ember version to 2.8-LTS along with updating `ember-cli-htmlbars` to the latest version in the 1.0 series. Hope that helped.

**Comment by r22cky** [comment]
Thanks! Will let you know soon how it goes @simenheg ! 😃

**Comment by tobiasWenger** [comment]
Thanks @simenheg! I tested the master branch in my project and it looks fine (At least in my scenario). Now it would be nice to publish the new version.

**Comment by simenheg** [comment]
Thanks for checking, @tobiasWenger. I've tagged a new version.

**Comment by tobiasWenger** [comment]
I'm glad I could help and thanks for your valuable work!

**Comment by r22cky** [comment]
@simenheg did you push the update to npm ? thanks again for your time! 😄

**Comment by simenheg** [comment]
It should be there now, @r22cky.

**Comment by r22cky** [comment]
Yes! It is! thank you very much @simenheg ! Great work!
